'use strict';

// Host-agent: authoritative game-state process.
//
// Responsibilities:
//   • Authenticate with the gateway as the host
//   • Accept/reject player joins; assign entity IDs
//   • Manage world entities: dropped items, placed building pieces
//   • Process ItemDropRequest / ItemPickupRequest
//   • Process InteractionRequest (BUILD)
//   • Confirm Death/Respawn requests
//   • Broadcast WorldState periodically (advancing time-of-day)
//   • Persist entity and world-state changes to SQLite via db.js
//   • Reconnect automatically on gateway disconnect

const net    = require('node:net');
const crypto = require('node:crypto');

const cfg = require('./config');
const db  = require('./db');
const { FrameDecoder } = require('./lib/frame-decoder');
const {
    MsgType,
    EntityKind,
    InteractionType,
    encodeFrame,
    encodeString,
    decodeString,
    encodeEntityDescriptor,
    encodeEntityState,
    decodeItemDropRequest,
    decodeItemPickupRequest,
    encodeItemPickupResult,
    encodeItemDropResult,
    decodeInteractionRequest,
    encodeInteractionResult,
    decodeZombieAttackRequest,
    encodeZombieDamageResult,
} = require('./lib/protocol');
const { stableNumericId } = require('./lib/id');
const { ZombieSimulation } = require('./world/zombie-simulation');
const fs   = require('node:fs');
const path = require('node:path');

// Generated by server/scripts/extract-zombie-data.js — see that script and
// research/04_ida_investigation_log.md Session 58 for provenance. Loaded
// gracefully: zombie simulation is simply disabled (no spawns/ticks) rather
// than crashing the whole host-agent if this hasn't been generated yet.
function loadWorldData() {
    const p = process.env.SDB_WORLD_DATA_PATH || path.join(__dirname, 'data', 'world-data.json');
    if (!fs.existsSync(p)) {
        console.warn('[host] server/src/data/world-data.json not found — run ' +
            'server/scripts/extract-zombie-data.js. Zombie simulation disabled.');
        return null;
    }
    try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
    catch (e) { console.error(`[host] failed to load world-data.json: ${e.message}`); return null; }
}

const SESSION_ID     = Buffer.from(crypto.randomUUID().replace(/-/g, ''), 'hex');
const MAX_INV_SLOTS  = 40;   // client-side inventory size
const AUTO_SLOT      = 0xFF; // targetSlot sentinel meaning "first free"

// ── HostAgent ─────────────────────────────────────────────────────────────────

class HostAgent {
    constructor() {
        this._socket     = null;
        this._decoder    = new FrameDecoder();
        this._state      = 'disconnected';
        this._stopped    = false;
        this._reconnectMs = 250;

        // Timers
        this._heartbeatTimer  = null;
        this._worldStateTimer = null;
        this._reconnectTimer  = null;
        this._zombieTickTimer = null;

        const worldData = loadWorldData();
        this._zombieSim = worldData ? new ZombieSimulation(worldData, () => this._randomEntityId()) : null;
        // Vehicles are static world objects at fixed spawn points (unlike
        // zombies, nothing spawns/simulates them — every client already has
        // its own native instance at these exact positions from level load).
        // Server's job is just to be the canonical health/fuel record; see
        // _broadcastVehicles().
        this._vehicleZones = worldData ? (worldData.spawnZones || []).filter(z => z.kind === 'vehicle') : [];
        this._vehiclesBroadcast = false;

        this._tick     = 0;
        this._revision = parseInt(db.getWorldState('revision', '0'), 10);
        this._timeOfDay = parseFloat(db.getWorldState('timeOfDay', '600'));

        // playerId(BigInt) → { connectionId, entityId, inventory }
        // inventory: Array(MAX_INV_SLOTS) of null | { itemId, quantity }
        this._players = new Map();

        // entityId(BigInt) → { entityType, posX, posY, posZ, yaw, state }
        // Loaded from DB on start; kept in sync with DB as changes happen.
        this._entities = new Map();
        this._loadEntities();
    }

    start() {
        this._stopped = false;
        this._connect();
    }

    stop() {
        this._stopped = true;
        this._clearTimers();
        if (this._socket) { this._socket.destroy(); this._socket = null; }
        this._state = 'disconnected';
    }

    // ── private ────────────────────────────────────────────────────────────

    // Load from the structured `entities` table (db.js) — plain rows now,
    // no more manually re-parsing concatenated raw frame bytes the way this
    // had to when world_entities stored opaque replay blobs.
    _loadEntities() {
        for (const e of db.getAllEntitiesFull()) {
            this._entities.set(BigInt(e.entityId), {
                kind: e.kind,
                quantity: e.attributes.quantity ?? 0,
                itemId: e.attributes.itemId ?? '',
                x: e.x, y: e.y, z: e.z, yaw: e.yaw,
            });
        }
        console.log(`[host] loaded ${this._entities.size} world entities from DB`);
    }

    _connect() {
        if (this._stopped) return;
        this._state = 'connecting';
        this._decoder.reset();

        const sock = net.createConnection(cfg.gatewayPort, '127.0.0.1');
        this._socket = sock;
        sock.on('connect', () => this._onConnect());
        sock.on('data',    (c) => this._onData(c));
        sock.on('error',   (e) => console.error(`[host] ${e.message}`));
        sock.on('close',   ()  => this._onClose());
    }

    _onConnect() {
        this._reconnectMs = 250;
        this._state = 'auth';
        console.log('[host] connected to gateway, authenticating …');
        this._socket.write(encodeFrame({
            type:      MsgType.HostAuthenticate,
            sessionId: SESSION_ID,
            worldId:   cfg.worldId,
            payload:   encodeString(cfg.hostSecret, 512),
        }));
    }

    _onData(chunk) {
        let frames;
        try { frames = this._decoder.push(chunk); }
        catch (e) { console.error(`[host] decode: ${e.message}`); this._socket.destroy(); return; }
        for (const f of frames) this._dispatch(f);
    }

    _dispatch(f) {
        if (this._state === 'auth') {
            if (f.type === MsgType.AuthenticationAccepted) {
                this._state = 'active';
                console.log('[host] authenticated – session ready');
                this._startTimers();
                this._broadcastVehicles();
            } else if (f.type === MsgType.AuthenticationRejected) {
                const r = f.payload.length >= 2 ? decodeString(f.payload) : '';
                console.error(`[host] auth rejected: ${r}`);
                this._socket.destroy();
            }
            return;
        }

        if (this._state !== 'active') return;

        switch (f.type) {

        // ── Join / leave ──────────────────────────────────────────────────────

        case MsgType.JoinRequest: {
            const entityId = stableNumericId(`player-entity:${f.playerId}`);
            this._players.set(f.playerId, {
                connectionId: f.connectionId,
                entityId,
                inventory:    Array(MAX_INV_SLOTS).fill(null),
            });
            this._socket.write(encodeFrame({
                type:         MsgType.JoinAccepted,
                connectionId: f.connectionId,
                sessionId:    SESSION_ID,
                worldId:      cfg.worldId,
                playerId:     f.playerId,
                entityId,
                tick:         this._tick,
                payload:      encodeString('', 64),
            }));
            console.log(`[host] player ${f.playerId} joined  eid=${entityId}`);
            break;
        }

        case MsgType.PlayerDisconnected: {
            const p = this._players.get(f.playerId);
            if (!p) break;
            this._players.delete(f.playerId);
            this._socket.write(encodeFrame({
                type:         MsgType.PlayerDisconnected,
                connectionId: p.connectionId,
                sessionId:    SESSION_ID,
                worldId:      cfg.worldId,
                playerId:     f.playerId,
                entityId:     p.entityId,
                payload:      encodeString('player_left', 128),
            }));
            console.log(`[host] player ${f.playerId} left`);
            break;
        }

        // ── Death / respawn ───────────────────────────────────────────────────

        case MsgType.DeathRequest: {
            const p = this._players.get(f.playerId);
            console.log(`[host] DeathRequest playerId=${f.playerId}  knownPlayer=${!!p}  trackedPlayerIds=[${[...this._players.keys()].join(',')}]`);
            if (!p) break;
            this._socket.write(encodeFrame({
                type:         MsgType.Death,
                connectionId: p.connectionId,
                sessionId:    SESSION_ID,
                worldId:      cfg.worldId,
                playerId:     f.playerId,
                entityId:     p.entityId,
                payload:      encodeString('host_confirmed_death', 128),
            }));
            break;
        }

        case MsgType.RespawnRequest: {
            const p = this._players.get(f.playerId);
            if (!p) break;
            this._socket.write(encodeFrame({
                type:         MsgType.Respawn,
                connectionId: p.connectionId,
                sessionId:    SESSION_ID,
                worldId:      cfg.worldId,
                playerId:     f.playerId,
                entityId:     p.entityId,
                payload:      encodeString('host_confirmed_respawn', 128),
            }));
            break;
        }

        // ── Player profile (client pushes its state so server can persist it) ─

        case MsgType.ProfileRevision:
            // The gateway already stored the raw payload to DB.
            // The host-agent updates the in-memory inventory by parsing it.
            this._applyProfileRevision(f);
            break;

        case MsgType.Equipment:
            // Equipment updates are informational for the host (future: validate loadout).
            break;

        case MsgType.WeaponAttachments:
            // Same as Equipment above — informational only, purely cosmetic.
            break;

        case MsgType.PawnAppearance:
            // Same as Equipment above — informational only, purely cosmetic.
            break;

        // ── Item drop ─────────────────────────────────────────────────────────

        case MsgType.ItemDropRequest: {
            const p = this._players.get(f.playerId);
            if (!p) break;
            try {
                const req = decodeItemDropRequest(f.payload);

                if (!req.itemId || req.quantity <= 0) {
                    p.connectionId && this._sendTo(p.connectionId, MsgType.ItemDropResult,
                        f.playerId, p.entityId,
                        encodeItemDropResult({ success: false, reason: 0 })); // 0 = slot_empty
                    break;
                }

                // Trust the client's itemId/quantity directly rather than
                // requiring a match in p.inventory — that array is only ever
                // populated from ProfileRevision's *container* contents
                // (Equipment messages are explicitly informational-only, see
                // the Equipment case above), so a drop of a currently
                // EQUIPPED/in-hand item (the common case — this hook fires
                // from the in-world drop action, not a backpack reorganize)
                // would never be found there and would always silently fail.
                // Same client-authoritative trust already given to
                // ProfileRevision's raw payload elsewhere in this file.
                const qty = req.quantity;
                const slotIndex = p.inventory.findIndex(
                    s => s && s.itemId === req.itemId && s.quantity > 0);
                if (slotIndex >= 0) {
                    // Best-effort bookkeeping when it does happen to be a
                    // tracked container item — not required for the drop to
                    // succeed.
                    const slot = p.inventory[slotIndex];
                    slot.quantity -= Math.min(qty, slot.quantity);
                    if (slot.quantity <= 0) p.inventory[slotIndex] = null;
                }

                // Spawn a world entity for the dropped item: descriptor frame
                // (kind/quantity/itemId, no position) followed by a state
                // frame (position) — see protocol.js encodeEntityDescriptor.
                const entityId = this._randomEntityId();
                this._entities.set(entityId, {
                    kind: EntityKind.GroundItem,
                    itemId: req.itemId, quantity: qty,
                    x: req.posX, y: req.posY, z: req.posZ, yaw: 0,
                });

                const descPayload = encodeEntityDescriptor({
                    kind: EntityKind.GroundItem,
                    quantity: qty,
                    ownerPlayerId: f.playerId,
                    itemId: req.itemId,
                });
                // Gateway intercepts EntitySpawn/EntityState and persists to DB.
                this._socket.write(encodeFrame({
                    type: MsgType.EntitySpawn, sessionId: SESSION_ID, worldId: cfg.worldId,
                    entityId, payload: descPayload,
                }));
                this._socket.write(encodeFrame({
                    type: MsgType.EntityState, sessionId: SESSION_ID, worldId: cfg.worldId,
                    entityId,
                    payload: encodeEntityState({
                        kind: EntityKind.GroundItem,
                        x: req.posX, y: req.posY, z: req.posZ, yaw: 0,
                    }),
                }));

                this._sendTo(p.connectionId, MsgType.ItemDropResult,
                    f.playerId, p.entityId,
                    encodeItemDropResult({ success: true }));

                console.log(`[host] player ${f.playerId} dropped item ${req.itemId}×${qty}  eid=${entityId}`);
            } catch (e) {
                console.error(`[host] ItemDropRequest: ${e.message}`);
            }
            break;
        }

        // ── Item pickup ───────────────────────────────────────────────────────

        case MsgType.ItemPickupRequest: {
            const p = this._players.get(f.playerId);
            if (!p) break;
            try {
                const req    = decodeItemPickupRequest(f.payload);
                const entity = this._entities.get(f.entityId);

                if (!entity || entity.kind !== EntityKind.GroundItem) {
                    this._sendTo(p.connectionId, MsgType.ItemPickupResult,
                        f.playerId, p.entityId,
                        encodeItemPickupResult({ success: false, reason: 0 })); // entity_gone
                    break;
                }

                const { itemId, quantity } = entity;
                const targetSlot = req.targetSlot === AUTO_SLOT
                    ? p.inventory.findIndex(s => s === null)
                    : req.targetSlot;

                if (targetSlot < 0 || targetSlot >= MAX_INV_SLOTS) {
                    this._sendTo(p.connectionId, MsgType.ItemPickupResult,
                        f.playerId, p.entityId,
                        encodeItemPickupResult({ success: false, reason: 1 })); // inv_full
                    break;
                }

                // Add to inventory
                p.inventory[targetSlot] = { itemId, quantity };
                this._entities.delete(f.entityId);
                db.deleteEntity(f.entityId);

                // Tell all clients the entity is gone.
                this._socket.write(encodeFrame({
                    type:      MsgType.EntityDespawn,
                    sessionId: SESSION_ID,
                    worldId:   cfg.worldId,
                    entityId:  f.entityId,
                    payload:   Buffer.from([1]), // reason=1: picked_up
                }));

                this._sendTo(p.connectionId, MsgType.ItemPickupResult,
                    f.playerId, p.entityId,
                    encodeItemPickupResult({ success: true, slot: targetSlot, itemId, quantity }));

                console.log(`[host] player ${f.playerId} picked up item ${itemId}×${quantity}  slot=${targetSlot}`);
            } catch (e) {
                console.error(`[host] ItemPickupRequest: ${e.message}`);
            }
            break;
        }

        // ── Building / interactions ───────────────────────────────────────────

        case MsgType.InteractionRequest: {
            const p = this._players.get(f.playerId);
            if (!p) break;
            try {
                const req = decodeInteractionRequest(f.payload);

                if (req.interactionType === InteractionType.BUILD) {
                    if (!req.itemId) {
                        this._sendTo(p.connectionId, MsgType.InteractionResult,
                            f.playerId, p.entityId,
                            encodeInteractionResult({ success: false, interactionType: InteractionType.BUILD }));
                        break;
                    }
                    const entityId = this._randomEntityId();

                    // itemId now names a real UJigsawItem_DataAsset_C (same
                    // as GroundItem) — entity_manager.cpp's spawn_entity_actor
                    // resolves it and reads BuildActorClass (not PickupClass)
                    // to find the specific piece class to spawn. Persistence
                    // to the unified entities table happens uniformly in
                    // gateway.js's EntitySpawn/EntityState handling, same as
                    // every other entity kind.
                    this._entities.set(entityId, {
                        kind: EntityKind.PlacedStructure,
                        itemId: req.itemId, quantity: 0,
                        x: req.posX, y: req.posY, z: req.posZ, yaw: req.yaw,
                    });

                    this._socket.write(encodeFrame({
                        type: MsgType.EntitySpawn, sessionId: SESSION_ID, worldId: cfg.worldId,
                        entityId,
                        payload: encodeEntityDescriptor({
                            kind: EntityKind.PlacedStructure,
                            ownerPlayerId: f.playerId,
                            itemId: req.itemId,
                        }),
                    }));
                    this._socket.write(encodeFrame({
                        type: MsgType.EntityState, sessionId: SESSION_ID, worldId: cfg.worldId,
                        entityId,
                        payload: encodeEntityState({
                            kind: EntityKind.PlacedStructure,
                            x: req.posX, y: req.posY, z: req.posZ, yaw: req.yaw,
                            health: 1.0,
                        }),
                    }));

                    this._sendTo(p.connectionId, MsgType.InteractionResult,
                        f.playerId, p.entityId,
                        encodeInteractionResult({ success: true, interactionType: InteractionType.BUILD }));

                    console.log(`[host] player ${f.playerId} placed piece ${req.itemId}  eid=${entityId}`);
                }
            } catch (e) {
                console.error(`[host] InteractionRequest: ${e.message}`);
            }
            break;
        }

        case MsgType.Movement: {
            // Already broadcast by gateway; host also gets a copy here so it
            // can track player positions for zombie-simulation relevance
            // scoping (server/src/world/zombie-simulation.js). Fixed 39-byte
            // format (protocol.hpp MOVEMENT_PAYLOAD_SIZE) — x/y/z are the
            // first three float32BE fields, no dedicated JS decoder needed
            // for just these three.
            const p = this._players.get(f.playerId);
            if (p && f.payload && f.payload.length >= 12) {
                p.lastPos = {
                    x: f.payload.readFloatBE(0),
                    y: f.payload.readFloatBE(4),
                    z: f.payload.readFloatBE(8),
                };
            }
            break;
        }

        // ── Zombie damage ─────────────────────────────────────────────────────

        case MsgType.ZombieAttackRequest: {
            if (!this._zombieSim) break;
            const p = this._players.get(f.playerId);
            if (!p) break;
            try {
                const req = decodeZombieAttackRequest(f.payload);
                const result = this._zombieSim.applyDamage(f.entityId, req.damage);
                if (!result) break; // not a zombie this simulation is tracking (already dead / never existed)

                this._sendTo(p.connectionId, MsgType.ZombieDamageResult,
                    f.playerId, f.entityId,
                    encodeZombieDamageResult({ newHealth: result.newHealth, dead: result.dead }));

                if (result.dead) {
                    this._socket.write(encodeFrame({
                        type: MsgType.EntityDespawn, sessionId: SESSION_ID, worldId: cfg.worldId,
                        entityId: f.entityId, payload: Buffer.from([2]), // reason=2: killed
                    }));
                } else {
                    // Must include the zombie's real current position, not a
                    // placeholder — gateway.js's EntityState handler upserts
                    // the full row, including x/y/z, so sending zeros here
                    // would silently teleport the stored (and broadcast)
                    // position to the origin.
                    const zombie = this._zombieSim.get(f.entityId);
                    this._socket.write(encodeFrame({
                        type: MsgType.EntityState, sessionId: SESSION_ID, worldId: cfg.worldId,
                        entityId: f.entityId,
                        payload: encodeEntityState({
                            kind: EntityKind.Zombie,
                            x: zombie ? zombie.x : 0, y: zombie ? zombie.y : 0,
                            z: zombie ? zombie.z : 0, yaw: zombie ? zombie.yaw : 0,
                            health: result.newHealth,
                        }),
                    }));
                }

                console.log(`[host] zombie ${f.entityId} took ${req.damage} damage from player ${f.playerId}  newHealth=${result.newHealth}  dead=${result.dead}`);
            } catch (e) {
                console.error(`[host] ZombieAttackRequest: ${e.message}`);
            }
            break;
        }

        } // switch
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    _sendTo(connectionId, type, playerId, entityId, payload) {
        this._socket.write(encodeFrame({
            type, connectionId, sessionId: SESSION_ID,
            worldId: cfg.worldId, playerId, entityId, payload,
        }));
    }

    _randomEntityId() {
        const bytes = crypto.randomBytes(8);
        const id    = bytes.readBigUInt64BE(0);
        return id === 0n ? 1n : id;
    }

    _applyProfileRevision(f) {
        const p = this._players.get(f.playerId);
        if (!p || f.payload.length < 51) return;
        try {
            const { containers, forename, surname, zombieKills, daysSurvived, bossZombieKills,
                     animalKills, humanKills, distanceTravelled, infestationsDestroyed } =
                decodePlayerProgress(f.payload);
            // p.inventory is a flat bookkeeping array used only for live
            // ItemPickupRequest/ItemDropRequest slot-targeting during this
            // session — the authoritative save data is the full container
            // list, persisted verbatim as raw bytes (see gateway.js
            // ProfileRevision handling), so flattening here is lossless for
            // what actually gets restored on rejoin. Items beyond
            // MAX_INV_SLOTS simply aren't targetable by slot index in this
            // bookkeeping array — that cap is local to pickup/drop, not the
            // wire format or the persisted save (gap 11).
            const inv = Array(MAX_INV_SLOTS).fill(null);
            for (const container of containers) {
                for (const item of container.items) {
                    if (item.slotIndex < MAX_INV_SLOTS && !inv[item.slotIndex])
                        inv[item.slotIndex] = { itemId: item.itemId, quantity: item.quantity };
                }
            }
            p.inventory = inv;
            // Extended stats trailer (gap 4/7) — absent (all defaults) on a
            // payload persisted before this trailer existed.
            p.stats = { forename, surname, zombieKills, daysSurvived, bossZombieKills,
                        animalKills, humanKills, distanceTravelled, infestationsDestroyed };
        } catch { /* malformed payload */ }
    }

    // ── Timers ────────────────────────────────────────────────────────────────

    _startTimers() {
        this._heartbeatTimer = setInterval(() => {
            if (this._state !== 'active') return;
            this._tick++;
            this._socket.write(encodeFrame({
                type:      MsgType.HostHeartbeat,
                sessionId: SESSION_ID,
                worldId:   cfg.worldId,
                flags:     1,
                tick:      this._tick,
            }));
        }, cfg.heartbeatMs);

        this._worldStateTimer = setInterval(() => {
            if (this._state !== 'active') return;
            this._broadcastWorldState();
        }, cfg.worldStateIntervalMs);

        if (this._zombieSim) {
            this._zombieTickTimer = setInterval(() => {
                if (this._state !== 'active') return;
                this._tickZombies();
            }, cfg.zombieTickIntervalMs);
        }
    }

    // Drives ZombieSimulation with currently-known player positions and
    // turns its returned spawn/update/despawn events into the same
    // EntitySpawn/EntityState/EntityDespawn wire frames every other entity
    // kind already uses — gateway.js persists them into the unified
    // entities table exactly the same way, no special-casing needed there.
    _tickZombies() {
        const positions = [...this._players.values()]
            .map(p => p.lastPos)
            .filter(Boolean);
        const { spawns, updates, despawns } = this._zombieSim.tick(positions);

        for (const s of spawns) {
            this._socket.write(encodeFrame({
                type: MsgType.EntitySpawn, sessionId: SESSION_ID, worldId: cfg.worldId,
                entityId: s.entityId,
                payload: encodeEntityDescriptor({
                    kind: EntityKind.Zombie,
                    itemId: s.archetype, // repurposed as a plain archetype-name string, not a JigsawItem itemId — client resolves via FindFirstOf(archetype), not resolve_item_asset()
                }),
            }));
            this._socket.write(encodeFrame({
                type: MsgType.EntityState, sessionId: SESSION_ID, worldId: cfg.worldId,
                entityId: s.entityId,
                payload: encodeEntityState({
                    kind: EntityKind.Zombie, x: s.x, y: s.y, z: s.z, yaw: s.yaw, health: s.health,
                }),
            }));
        }
        for (const u of updates) {
            this._socket.write(encodeFrame({
                type: MsgType.EntityState, sessionId: SESSION_ID, worldId: cfg.worldId,
                entityId: u.entityId,
                payload: encodeEntityState({
                    kind: EntityKind.Zombie, x: u.x, y: u.y, z: u.z, yaw: u.yaw, health: u.health,
                }),
            }));
        }
        for (const d of despawns) {
            this._socket.write(encodeFrame({
                type: MsgType.EntityDespawn, sessionId: SESSION_ID, worldId: cfg.worldId,
                entityId: d.entityId, payload: Buffer.from([2]), // reason=2: killed
            }));
        }
    }

    // Vehicles are static — no spawning/simulation, no tick. Broadcast once
    // per session (not on a repeating timer like zombies) so every client's
    // entity_manager.cpp can correlate each entityId to its own already-
    // existing native vehicle actor at that position (the same nearest-
    // position-match technique already proven for GroundItem's own-drop
    // claiming, entity_manager.cpp's find_and_claim_native_pickup — no
    // spawning, no class resolution, none of the risk that caused zombie
    // proxy rendering's crash saga). entityId is derived from the spawner's
    // stable name (stableNumericId, same helper player entityIds use) so it
    // stays consistent across server restarts. Health/fuel start at their
    // real confirmed base defaults (research/04_ida_investigation_log.md —
    // VehicleHealthComponent/VehicleFuelComponent both default to 100)
    // rather than a guess.
    _broadcastVehicles() {
        if (this._vehiclesBroadcast || this._vehicleZones.length === 0) return;
        this._vehiclesBroadcast = true;

        for (const zone of this._vehicleZones) {
            const entityId = stableNumericId(`vehicle-spawn:${zone.name}`);
            this._socket.write(encodeFrame({
                type: MsgType.EntitySpawn, sessionId: SESSION_ID, worldId: cfg.worldId,
                entityId,
                payload: encodeEntityDescriptor({ kind: EntityKind.Vehicle }),
            }));
            this._socket.write(encodeFrame({
                type: MsgType.EntityState, sessionId: SESSION_ID, worldId: cfg.worldId,
                entityId,
                payload: encodeEntityState({
                    kind: EntityKind.Vehicle, x: zone.x, y: zone.y, z: zone.z, yaw: zone.yaw,
                    health: 100,
                }),
            }));
        }
        console.log(`[host] broadcast ${this._vehicleZones.length} vehicle entities`);
    }

    _broadcastWorldState() {
        const msPerGameHour = 3_600_000 / 4;
        this._timeOfDay = (this._timeOfDay + (cfg.worldStateIntervalMs / msPerGameHour) * 100) % 2400;
        this._revision++;

        // Persist every ~60 s (avoid thrashing on every 2 s interval).
        if (this._revision % 30 === 0) {
            db.setWorldState('timeOfDay', this._timeOfDay);
            db.setWorldState('revision',  this._revision);
        }

        const payload = Buffer.allocUnsafe(41);
        let o = 0;
        payload.writeUInt8(1, o);                               o += 1;
        payload.writeUInt32BE(this._revision, o);               o += 4;
        payload.writeBigUInt64BE(BigInt(Date.now()), o);        o += 8;
        payload.writeFloatBE(this._timeOfDay, o);               o += 4;
        payload.writeFloatBE(0.0, o);                           o += 4;
        payload.writeFloatBE(0.0, o);                           o += 4;
        payload.writeFloatBE(0.1, o);                           o += 4;
        payload.writeFloatBE(0.4, o);                           o += 4;
        payload.writeFloatBE(0.1, o);                           o += 4;
        payload.writeFloatBE(0.0, o);

        this._socket.write(encodeFrame({
            type:      MsgType.WorldState,
            sessionId: SESSION_ID,
            worldId:   cfg.worldId,
            sequence:  this._revision,
            tick:      this._tick,
            payload,
        }));
    }

    _onClose() {
        console.log('[host] disconnected from gateway');
        this._clearTimers();
        this._socket = null;
        this._state  = 'disconnected';
        this._decoder.reset();
        if (!this._stopped) {
            console.log(`[host] reconnecting in ${this._reconnectMs}ms`);
            this._reconnectTimer = setTimeout(() => {
                this._reconnectMs = Math.min(this._reconnectMs * 2, 5_000);
                this._connect();
            }, this._reconnectMs);
        }
    }

    _clearTimers() {
        if (this._heartbeatTimer)  { clearInterval(this._heartbeatTimer);  this._heartbeatTimer  = null; }
        if (this._worldStateTimer) { clearInterval(this._worldStateTimer); this._worldStateTimer = null; }
        if (this._zombieTickTimer) { clearInterval(this._zombieTickTimer); this._zombieTickTimer = null; }
        if (this._reconnectTimer)  { clearTimeout(this._reconnectTimer);   this._reconnectTimer  = null; }
    }
}

module.exports = { HostAgent };
